### ISSUE TITLE
Replacing user's link breaks image detail view

### ISSUE THREAD

**Issue by andyboeh** [geekitude/dokuwiki-plugin-userhomepage#16] opened 2015-10-03 14:04 UTC
I just enabled the option to replace the user name with a link to his namespace. Unfortunately, this broke image's detailed view and results in a page with only the DokuWiki logo.

I debugged a bit, it seems that DOKUWIKI_STARTED is never emitted for image details, thus the plugin isn't correctly initialized and hence the helper plugin is not available.

**Comment by geekitude** [comment] 2015-10-03 14:28
Hi

Sorry for that bug... The good news is that I have been abble to reproduce it ;)
I'll try to fix it asap.

**Comment by geekitude** [comment] 2015-10-03 14:43
Fixed by also initializing on 'DETAIL_STARTED' event.
New version released and ready to download from plugins administration.

Thanks for the nice debugging ;)

**Comment by geekitude** [comment] 2016-02-20 08:08
This bug is back (or more likely still there) :(
If the option to replace user link is enabled, it breaks images' detailed view. This time it is because plugin tries to create user's public and/or private pages within Dokuwiki's media folder.

**Comment by geekitude** [comment] 2016-05-16 20:07
Fixed [here](https://github.com/geekitude/dokuwiki-plugin-userhomepage/commit/f88ba74523829ee03ef5f38629d7a232cc444069).

Can now be closed since it's been a few months and the problem didn't occure again.

**Closed by geekitude** 2016-05-16 20:07 UTC
Labels: bug
