### ISSUE TITLE
Cannot use ACL manage

### ISSUE THREAD

**Issue by renwanly** [geekitude/dokuwiki-plugin-userhomepage#36] opened 2020-02-08 10:28 UTC
The ACL manage will redirect to user homepage automatically when submit, and the ACL settings will never changed.

----
[DokuWiki Ver]：2018-04-22 "Greebo" 

[DokuWiki Plugins ENABLED]:
Add New Page
AV Bar Chart
BackupTool for DokuWiki
CAPTCHA Plugin
Code Prettifier
comment
discussion plugin
Dw2Pdf plugin
hidden Plugin
Icons Plugin
include plugin
noprint Plugin
Open Document Plugin
Searchindex Manager
SearchPattern plugin
simpleindex plugin
smtp plugin 
sqlite plugin
struct plugin
ToDo
Translation Plugin
DokuWiki Upgrade Plugin
User Homepage
Video Sharing Site Plugin
Generic WebDAV Client PlugIn
Wiki-Style Script
Wrap Plugin

[userhomepage Ver]：2019-01-19

[userhomepage config]: 
create_private_ns: Yes
use_name_string: No
use_start_page: Yes
users_namespace: user
group_by_name: No
edit_before_create: No
acl_all_private: Default
acl_user_private: Default
groups_private: 
create_public_page: Yes
public_pages_ns: user
acl_all_public: None
acl_user_public: Default
groups_public: 
templates_path: ./pages/user
templatepath: lib/plugins/userhomepage/_template.txt
acl_all_templates: None
acl_user_templates: Default
no_acl: No
redirection: Yes
action: Default
userlink_replace: Yes
userlink_classes: interwiki iw_user
userlink_fa: No

**Comment by geekitude** [comment] 2020-02-13 07:03
Hello

Sorry for the late answer but I was away from home.

I haven't been able to reproduce the issue on a brand new install of Dokuwiki but I guess it would be a nice thing to prevent redirection whenever url points to an action page (ie. when it contains any 'do' value).

Can you please update the plugin and keep me informed?

**Comment by renwanly** [comment] 2020-02-14 09:16
I'd test ver.2020-02-13 of this plugin, and the problem is still there. :-(

Not only the ACL setting, but also all of the manage functions could not save when `redirection` value is setting to`1`.

The following code is part of the file 
`/conf/local.php`

`$conf['plugin']['userhomepage']['create_private_ns'] = 1;`
`$conf['plugin']['userhomepage']['acl_all_private'] = 'noacl';`
`$conf['plugin']['userhomepage']['create_public_page'] = 1;`
`$conf['plugin']['userhomepage']['acl_all_public'] = 'noacl';`
`$conf['plugin']['userhomepage']['acl_all_templates'] = 'noacl';`
`$conf['plugin']['userhomepage']['acl_user_templates'] = 'noacl';`
`$conf['plugin']['userhomepage']['userlink_replace'] = 0;`
`$conf['plugin']['userhomepage']['userlink_fa'] = 1;`

**Comment by geekitude** [comment] 2020-02-15 11:18
Still can't reproduce the problem but a released a new version to try ;)

Delayed redirection test a little (I expect to get more accurate environment variable values). I also added a few lines we might use for testing if this version still doesn't help.

**Comment by geekitude** [comment] 2020-08-16 09:24
6months without feedback.
Closing this issue.

**Closed by geekitude** 2020-08-16 09:24 UTC
